# Generated by Django 4.1.5 on 2023-01-16 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('color', models.CharField(max_length=7, verbose_name='color')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200, verbose_name='caption')),
                ('text', models.TextField(verbose_name='text')),
                ('image', models.ImageField(upload_to='posts/images/', verbose_name='image')),
                ('meeted_at', models.CharField(choices=[('Outdoors', 'Outdoors'), ('Indoors', 'Indoors'), ('Mixed', 'Mixed')], max_length=20)),
                ('feeded', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='caption')),
                ('downvotes', models.ManyToManyField(blank=True, related_name='posts_downvoted', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(default='-empty-', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to='posts.season', verbose_name='posts')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='posts_upvoted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-pub_date',),
            },
        ),
    ]
