# Generated by Django 4.1.5 on 2023-01-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='season',
            field=models.ForeignKey(default='-empty-', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to='posts.season', verbose_name='season'),
        ),
    ]
