version: "3.8"

services:

  db:
    image: postgres:latest
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  backend:
    build: 
      context: ../backend/
    command: gunicorn app_config.wsgi --bind 0.0.0.0:8000
    # ports:
    #   - "8000:8000"
    volumes:
      - static_value:/backend/static_backend/
      - media_value:/backend/media_backend/
    depends_on:
      - db
    env_file:
      - ./.env
  
  frontend:
    build:
      context: ../frontend/
    volumes:
      - frontend_build:/frontend/build

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media_backend/
      - frontend_build:/var/www/frontend
    depends_on:
      - backend
      - frontend
  
volumes:
  postgresql_data:
  frontend_build:
  static_value:
  media_value: